apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-vfhh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-vfhh
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-vfhh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-vfhh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-vfhh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vbil-tenant/rhtap-demo-app/hacbs-test-project-vfhh@sha256:bcbf43eabbd57fa4bbd10b108d9e3a8bae8e68ae4b2d022144d4650c39cc877c
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
